### ISSUE TITLE
MCPE iOS v0.1.3.0 sees registred Dragonet servers as offline

### ISSUE THREAD

**Issue by jlirochon** [DragonetMC/Dragonet-Legacy#108] opened 2015-12-03 10:22 UTC
If I manually register Dragonet server on my client, it is listed by the client, but the client is unable to retrieve information about the server.

The servers appears offline / not responding, but If I choose it, I can connect !

Should be a problem in status response from the server.

**Comment by DefinitlyEvil** [comment] 2015-12-03 11:38
This is caused by invalid broadcast response. Duplicated issue so I am closing it. ;) Thanks for checking it out.

**Closed as completed** 2015-12-03 11:38 UTC
Labels: OLD
